# Generated by Django 2.2.7 on 2020-09-22 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mywed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('favour', models.IntegerField(default=0)),
                ('type_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywed.TypeStory')),
            ],
        ),
    ]
