# Generated by Django 2.2.7 on 2020-10-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywed', '0003_auto_20201002_0447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='animal_type',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='score',
        ),
        migrations.AddField(
            model_name='animal',
            name='detail',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='animal',
            name='img',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='animal',
            name='video',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='animal_type',
            name='text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
